name: Multi-Architecture Tests

on:
  push:
    # branches: [ main ]
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86_64
          - os: ubuntu-latest
            target: x86_64-linux
          # Linux aarch64
          - os: ubuntu-latest
            target: aarch64-linux
          # macOS x86_64
          - os: macos-13
            target: x86_64-macos
          # macOS aarch64 (Apple Silicon)
          - os: macos-latest
            target: aarch64-macos
          # Windows x86_64
          - os: windows-latest
            target: x86_64-windows
          # Linux RISC-V 64
          - os: ubuntu-latest
            target: riscv64-linux

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Zig
      - run: zig build test
      - uses: mlugg/setup-zig@v2
        # uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.1  # or specify a version like "0.13.0"
      
      - name: Run tests
        run: zig build test -Dtarget=${{ matrix.target }}
      
      - name: Run tests (native) on matching platform
        if: |
          (matrix.target == 'x86_64-linux' && matrix.os == 'ubuntu-latest') ||
          (matrix.target == 'x86_64-macos' && matrix.os == 'macos-13') ||
          (matrix.target == 'aarch64-macos' && matrix.os == 'macos-latest') ||
          (matrix.target == 'x86_64-windows' && matrix.os == 'windows-latest')
        run: zig build test
